// utils/pdfGenerator.ts
import jsPDF from "jspdf";

export function generatePDF(reportData: any): jsPDF {
  const doc = new jsPDF();
  let y = 20;
  
  // Header
  doc.setFillColor(46, 125, 50);
  doc.rect(0, 0, 210, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("Crop Insurance Report", 105, 25, { align: "center" });
  
  doc.setTextColor(0, 0, 0);
  y = 55;
  
  // Farmer Details
  doc.setFontSize(14);
  doc.text("Farmer Details", 20, y);
  y += 10;
  doc.setFontSize(10);
  doc.text(`Name: ${reportData.farmer.name}`, 20, y);
  y += 7;
  doc.text(`Aadhaar: ${reportData.farmer.aadhaar}`, 20, y);
  y += 7;
  doc.text(`Village: ${reportData.farmer.village}`, 20, y);
  y += 7;
  doc.text(`District: ${reportData.farmer.district}`, 20, y);
  y += 15;
  
  // Farm Details
  doc.setFontSize(14);
  doc.text("Farm Details", 20, y);
  y += 10;
  doc.setFontSize(10);
  doc.text(`Crop: ${reportData.farm.cropType}`, 20, y);
  y += 7;
  doc.text(`Area: ${reportData.farm.areaHectares} hectares`, 20, y);
  y += 7;
  doc.text(`Season: ${reportData.farm.season}`, 20, y);
  y += 7;
  doc.text(`Sowing Date: ${new Date(reportData.farm.sowingDate).toLocaleDateString()}`, 20, y);
  y += 15;
  
  // NDVI Analysis
  doc.setFontSize(14);
  doc.text("NDVI Analysis", 20, y);
  y += 10;
  doc.setFontSize(10);
  doc.text(`NDVI Value: ${reportData.analysis?.ndviValue?.toFixed(4) || "N/A"}`, 20, y);
  y += 7;
  doc.text(`Health: ${reportData.analysis?.healthPercentage || 0}%`, 20, y);
  y += 7;
  doc.text(`Damage: ${reportData.analysis?.damagePercentage || 0}%`, 20, y);
  y += 7;
  doc.text(`Risk Level: ${reportData.analysis?.riskLevel || "Low"}`, 20, y);
  y += 15;
  
  // Financial
  doc.setFontSize(14);
  doc.text("Financial Assessment", 20, y);
  y += 10;
  doc.setFontSize(10);
  const estimatedLoss = reportData.analysis?.estimatedLoss || 0;
  doc.text(`Estimated Loss: ₹${estimatedLoss.toLocaleString()}`, 20, y);
  y += 7;
  doc.text(`Compensation (72%): ₹${Math.round(estimatedLoss * 0.72).toLocaleString()}`, 20, y);
  y += 15;
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text("Generated by CropSafe Satellite Crop Insurance System", 105, 280, { align: "center" });
  
  return doc;
}