import React, { createContext, useContext, useState, useCallback } from "react";
import type { Language } from "@/types";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  english: {
    "app.name": "CropSafe",
    "app.tagline": "Satellite Crop Insurance",
    "nav.home": "Home",
    "nav.dashboard": "Dashboard",
    "nav.farm": "My Farm",
    "nav.weather": "Weather",
    "nav.analysis": "Analysis",
    "nav.claims": "Claims",
    "nav.disease": "Disease",
    "nav.admin": "Admin",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "login.title": "Login",
    "login.farmer": "Farmer",
    "login.admin": "Admin",
    "login.aadhaar": "Aadhaar Number",
    "login.password": "Password",
    "login.button": "Login",
    "login.register": "New Farmer? Register",
    "login.forgot": "Forgot Password?",
    "register.title": "Register",
    "register.step1": "Personal",
    "register.step2": "Address",
    "register.step3": "Farm",
    "register.step4": "Verify",
    "register.name": "Full Name",
    "register.mobile": "Mobile Number",
    "register.village": "Village",
    "register.district": "District",
    "register.city": "City",
    "register.state": "State",
    "register.crop": "Select Crop Type",
    "register.season": "Select Season",
    "register.sowingDate": "Sowing Date",
    "register.terms": "I accept the terms and conditions",
    "register.submit": "Register",
    "dashboard.welcome": "Welcome",
    "dashboard.myFarm": "My Farm",
    "dashboard.cropHealth": "Crop Health",
    "dashboard.insurance": "Insurance",
    "dashboard.askAI": "Ask AI",
    "dashboard.weather": "Weather",
    "farm.health": "Health",
    "farm.damage": "Damage",
    "farm.area": "Area",
    "farm.crop": "Crop",
    "farm.season": "Season",
    "farm.sowingDate": "Sowing Date",
    "farm.status": "Status",
    "farm.recommendation": "AI Recommendation",
    "analysis.ndvi": "NDVI Value",
    "analysis.health": "Health",
    "analysis.damage": "Damage",
    "analysis.loss": "Estimated Loss",
    "analysis.risk": "Risk Level",
    "analysis.run": "Run New Analysis",
    "analysis.submitClaim": "Submit Claim",
    "analysis.generateReport": "Generate Report",
    "claims.title": "Insurance Claims",
    "claims.pending": "Pending",
    "claims.review": "Under Review",
    "claims.approved": "Approved",
    "claims.submit": "Submit Claim",
    "claims.amount": "Claim Amount",
    "claims.history": "Claim History",
    "disease.title": "Disease Detector",
    "disease.camera": "Camera",
    "disease.upload": "Upload",
    "disease.analyze": "Analyze",
    "disease.analyzing": "Analyzing...",
    "disease.severity": "Severity",
    "disease.symptoms": "Symptoms",
    "disease.treatment": "Treatment",
    "disease.prevention": "Prevention",
    "report.title": "Report Generator",
    "report.download": "Download PDF",
    "weather.title": "Weather",
    "profile.title": "Profile",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.success": "Success!",
  },
  hindi: {
    "app.name": "CropSafe",
    "app.tagline": "उपग्रह फसल बीमा",
    "nav.home": "होम",
    "nav.dashboard": "डैशबोर्ड",
    "nav.farm": "मेरा खेत",
    "nav.weather": "मौसम",
    "nav.analysis": "विश्लेषण",
    "nav.claims": "दावे",
    "nav.disease": "रोग",
    "nav.admin": "एडमिन",
    "nav.profile": "प्रोफाइल",
    "nav.logout": "लॉग आउट",
    "login.title": "लॉगिन",
    "login.farmer": "किसान",
    "login.admin": "एडमिन",
    "login.aadhaar": "आधार नंबर",
    "login.password": "पासवर्ड",
    "login.button": "लॉगिन",
    "login.register": "नए किसान? रजिस्टर करें",
    "login.forgot": "पासवर्ड भूल गए?",
    "register.title": "रजिस्टर",
    "register.step1": "व्यक्तिगत",
    "register.step2": "पता",
    "register.step3": "खेत",
    "register.step4": "जांचें",
    "register.name": "पूरा नाम",
    "register.mobile": "मोबाइल नंबर",
    "register.village": "गांव",
    "register.district": "जिला",
    "register.city": "शहर",
    "register.state": "राज्य",
    "register.crop": "फसल प्रकार चुनें",
    "register.season": "मौसम चुनें",
    "register.sowingDate": "बुवाई तिथि",
    "register.terms": "मैं नियम और शर्तें स्वीकार करता हूं",
    "register.submit": "रजिस्टर",
    "dashboard.welcome": "स्वागत है",
    "dashboard.myFarm": "मेरा खेत",
    "dashboard.cropHealth": "फसल स्वास्थ्य",
    "dashboard.insurance": "बीमा",
    "dashboard.askAI": "AI से पूछें",
    "dashboard.weather": "मौसम",
    "farm.health": "स्वास्थ्य",
    "farm.damage": "नुकसान",
    "farm.area": "क्षेत्र",
    "farm.crop": "फसल",
    "farm.season": "मौसम",
    "farm.sowingDate": "बुवाई तिथि",
    "farm.status": "स्थिति",
    "farm.recommendation": "AI सिफारिश",
    "analysis.ndvi": "NDVI मान",
    "analysis.health": "स्वास्थ्य",
    "analysis.damage": "नुकसान",
    "analysis.loss": "अनुमानित हानि",
    "analysis.risk": "जोखिम स्तर",
    "analysis.run": "नया विश्लेषण चलाएं",
    "analysis.submitClaim": "दावा जमा करें",
    "analysis.generateReport": "रिपोर्ट बनाएं",
    "claims.title": "बीमा दावे",
    "claims.pending": "लंबित",
    "claims.review": "समीक्षा में",
    "claims.approved": "स्वीकृत",
    "claims.submit": "दावा जमा करें",
    "claims.amount": "दावा राशि",
    "claims.history": "दावा इतिहास",
    "disease.title": "रोग पहचान",
    "disease.camera": "कैमरा",
    "disease.upload": "अपलोड",
    "disease.analyze": "विश्लेषण",
    "disease.analyzing": "विश्लेषण हो रहा है...",
    "disease.severity": "गंभीरता",
    "disease.symptoms": "लक्षण",
    "disease.treatment": "उपचार",
    "disease.prevention": "रोकथाम",
    "report.title": "रिपोर्ट जनरेटर",
    "report.download": "PDF डाउनलोड",
    "weather.title": "मौसम",
    "profile.title": "प्रोफाइल",
    "common.save": "सेव",
    "common.cancel": "रद्द करें",
    "common.loading": "लोड हो रहा है...",
    "common.error": "कुछ गलत हो गया",
    "common.success": "सफल!",
  },
  marathi: {
    "app.name": "CropSafe",
    "app.tagline": "उपग्रह पिक विमा",
    "nav.home": "मुख्य",
    "nav.dashboard": "डॅशबोर्ड",
    "nav.farm": "माझे शेत",
    "nav.weather": "हवामान",
    "nav.analysis": "विश्लेषण",
    "nav.claims": "दावे",
    "nav.disease": "रोग",
    "nav.admin": "प्रशासक",
    "nav.profile": "प्रोफाइल",
    "nav.logout": "लॉग आउट",
    "login.title": "लॉगिन",
    "login.farmer": "शेतकरी",
    "login.admin": "प्रशासक",
    "login.aadhaar": "आधार क्रमांक",
    "login.password": "पासवर्ड",
    "login.button": "लॉगिन",
    "login.register": "नवीन शेतकरी? नोंदणी करा",
    "login.forgot": "पासवर्ड विसरलात?",
    "register.title": "नोंदणी",
    "register.step1": "वैयक्तिक",
    "register.step2": "पत्ता",
    "register.step3": "शेत",
    "register.step4": "तपासणी",
    "register.name": "पूर्ण नाव",
    "register.mobile": "मोबाइल क्रमांक",
    "register.village": "गाव",
    "register.district": "जिल्हा",
    "register.city": "शहर",
    "register.state": "राज्य",
    "register.crop": "पिकाचा प्रकार निवडा",
    "register.season": "हंगाम निवडा",
    "register.sowingDate": "पेरणी तारीख",
    "register.terms": "मी नियम व अटी स्वीकारतो",
    "register.submit": "नोंदणी करा",
    "dashboard.welcome": "स्वागत आहे",
    "dashboard.myFarm": "माझे शेत",
    "dashboard.cropHealth": "पिकाचे आरोग्य",
    "dashboard.insurance": "विमा",
    "dashboard.askAI": "AI ला विचारा",
    "dashboard.weather": "हवामान",
    "farm.health": "आरोग्य",
    "farm.damage": "नुकसान",
    "farm.area": "क्षेत्र",
    "farm.crop": "पीक",
    "farm.season": "हंगाम",
    "farm.sowingDate": "पेरणी तारीख",
    "farm.status": "स्थिती",
    "farm.recommendation": "AI शिफारस",
    "analysis.ndvi": "NDVI मूल्य",
    "analysis.health": "आरोग्य",
    "analysis.damage": "नुकसान",
    "analysis.loss": "अंदाजे तोटा",
    "analysis.risk": "जोखीम पातळी",
    "analysis.run": "नवीन विश्लेषण चालवा",
    "analysis.submitClaim": "दावा सादर करा",
    "analysis.generateReport": "अहवाल तयार करा",
    "claims.title": "विमा दावे",
    "claims.pending": "प्रलंबित",
    "claims.review": "पुनरावलोकनाधीन",
    "claims.approved": "मंजूर",
    "claims.submit": "दावा सादर करा",
    "claims.amount": "दावा रक्कम",
    "claims.history": "दावा इतिहास",
    "disease.title": "रोग शोध",
    "disease.camera": "कॅमेरा",
    "disease.upload": "अपलोड",
    "disease.analyze": "विश्लेषण",
    "disease.analyzing": "विश्लेषण सुरू आहे...",
    "disease.severity": "गंभीरता",
    "disease.symptoms": "लक्षणे",
    "disease.treatment": "उपचार",
    "disease.prevention": "प्रतिबंध",
    "report.title": "अहवाल जनरेटर",
    "report.download": "PDF डाउनलोड",
    "weather.title": "हवामान",
    "profile.title": "प्रोफाइल",
    "common.save": "जतन करा",
    "common.cancel": "रद्द करा",
    "common.loading": "लोड होत आहे...",
    "common.error": "काहीतरी चूक झाली",
    "common.success": "यशस्वी!",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("language") as Language) || "english";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language]?.[key] || translations.english[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
